hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - trainer.init.optimizer.lr=0.0005,0.001,0.005
    - trainer.init.optimizer.weight_decay=0.0,0.0005,0.001
    - trainer.init.scheduler.gamma=1.0
    - trainer.init.scheduler.step_size=10
  job:
    name: run
    chdir: null
    override_dirname: trainer.init.optimizer.lr=0.0005,0.001,0.005,trainer.init.optimizer.weight_decay=0.0,0.0005,0.001,trainer.init.scheduler.gamma=1.0,trainer.init.scheduler.step_size=10
    id: ???
    num: ???
    config_name: run.yaml
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /home/andreas-linus-thalund-midtgaard/Desktop/Deep Learning/deep-learning-gnn-project/src
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/andreas-linus-thalund-midtgaard/Desktop/Deep Learning/deep-learning-gnn-project/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      model: gcn
      logger: wandb
      trainer: semi-supervised-ensemble
      dataset: qm9
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
dataset:
  dataset_name: qm9
  num_outputs: 1
  init:
    _target_: qm9.QM9DataModule
    data_augmentation: false
    name: qm9
    target: 2
    data_dir: ./data
    batch_size_train: 100
    batch_size_inference: 2048
    num_workers: 4
    splits:
    - 0.72
    - 0.08
    - 0.1
    - 0.1
    seed: 0
    subset_size: null
trainer:
  method: semi-supervised-ensemble
  train:
    total_epochs: 250
    validation_interval: 10
  init:
    _target_: trainer.SemiSupervisedEnsemble
    supervised_criterion:
      _target_: torch.nn.MSELoss
    optimizer:
      _target_: torch.optim.AdamW
      _partial_: true
      lr: 0.001
      weight_decay: 0.005
    scheduler:
      _target_: torch.optim.lr_scheduler.StepLR
      _partial_: true
      step_size: 10
      gamma: 1.0
logger:
  _target_: logger.WandBLogger
  group: ${dataset.dataset_name}
  name: ${model.name}_lr=${trainer.init.optimizer.lr}_wd=${trainer.init.optimizer.weight_decay}_seed=${seed}
  job_type: test
  entity: andrezzb-deep-learning-gnn
  project_name: deep-learning-gnn
  disable: false
  local_dir: ./logs
model:
  name: gcn
  init:
    _target_: models.GCN
    _partial_: false
    num_node_features: 11
seed: 0
device: unset
force_deterministic: false
debug_mode: false
result_dir: ./results
compile_model: false
